name = "ClusterStructureAnalysis"
uuid = "2442c3d4-a72b-48e4-981e-1ec681d20b6e"
authors = ["Elke Pahl <Elke.Pahl@auckland.ac.nz> and A.J. Tyler <atyl386@aucklanduni.ac.nz> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
